backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Segments"
    name: "segments"
    editor:
      preview: false
    files:
      - name: 'about'
        label: 'About'
        format: 'json'
        file: 'content/about.json'
        fields:
          - label: "Heading"
            name: "heading"
            widget: "object"
            fields:
              - { label: "Part 1", name: "part1", widget: "string", required: true }
              - { label: "Part 2", name: "part2", widget: "string", required: true }
          - label: "Additional text"
            name: "additionalText"
            widget: "object"
            fields:
              - { label: "Text before", name: "textBefore", widget: "string", required: true }
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string", required: true }
                  - { label: "Url", name: "href", widget: "string", required: true }
              - { label: "Text after", name: "textAfter", widget: "string", required: true }
      - name: 'Statistics'
        label: 'Statistics'
        format: 'json'
        file: 'content/statistics.json'
        widget: "object"
        fields:
          - { label: "Text 1", name: "part1", widget: "string", required: true }
          - { label: "Text 2", name: "part2", widget: "string", required: true }
          - label: "Text 3"
            name: "part3"
            widget: "object"
            fields:
              - { label: "Singular", name: "singular", widget: "string", required: true }
              - { label: "Plural", name: "plural", widget: "string", required: true }
      - name: 'skills'
        label: 'Skills'
        format: 'json'
        file: 'content/skills.json'
        fields:
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: true }
              - { label: "List", name: "list", widget: "markdown", buttons: ["bold", "link", "bulleted-list"], editor_components: [], mode: "rich_text", minimal: true, required: true }
          - label: "Visual output"
            name: "visualOutput"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: true }
              - { label: "List", name: "list", widget: "markdown", buttons: ["bold", "link", "bulleted-list"], editor_components: [], mode: "rich_text", minimal: true, required: true }
          - label: "Programming logic"
            name: "programmingLogic"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: true }
              - { label: "List", name: "list", widget: "markdown", buttons: ["bold", "link", "bulleted-list"], editor_components: [], mode: "rich_text", minimal: true, required: true }
      - name: 'education'
        label: 'Education'
        format: 'json'
        file: 'content/education.json'
        fields:
          - { label: "Show on page", name: "isVisible", widget: "boolean" }
          - { label: "Heading", name: "heading", widget: "string", required: true }
          - { label: "Text", name: "richText", widget: "markdown", buttons: ["bold", "link"], editor_components: [], mode: "rich_text", minimal: true, required: true }
      - name: 'certificatesAndConferences'
        label: 'Certificates and conferences'
        format: 'json'
        file: 'content/certificates-and-conferences.json'
        fields:
          - { label: "Show on page", name: "isVisible", widget: "boolean" }
          - { label: "Heading", name: "heading", widget: "string", required: true }
          - { label: "List", name: "list", widget: "markdown", buttons: ["heading-three", "bold", "link", "bulleted-list"], editor_components: [], mode: "rich_text", minimal: true, required: true }
